### ISSUE TITLE
24.04.2015 GCW Zero build stuck at "Drawing Level" screen

### ISSUE THREAD

**Issue by zear** [theZiz/hase#1]
![screenshot255](https://cloud.githubusercontent.com/assets/510643/7335250/0d89fa6c-ebb2-11e4-9f72-48cd35ecd630.png)

Game menus/lobby/chat - all working fine. But the game gets stuck at the screen above with 100% cpu usage the moment a level is launched.

**Comment by theZiz** [comment]
Interesting, on the pandora and PC the game crashes with a segfault with a chance of ~10% at the very same position. The problem is a corrupted player position list. Until now I don't know, why this happens, but when I fixed this bug, your bug is gone hopefully, too. Do you know, whether version 1.5.2 was still working?

**Comment by theZiz** [comment]
Oh and does this happen for local and online games?

**Comment by zear** [comment]
It happens on both online and local games.

**Comment by theZiz** [comment]
Oh, I forgot about this: Probably fixed.

**Comment by zear** [comment]
I confirm it's fixed in the 28.04.2015 build.
