### ISSUE TITLE
Can't connect to chat on port 6666, 6667 works.

### ISSUE THREAD

**Issue by klopsi** [theZiz/hase#8]
Found the issue i was having with hase and chat.  Neither hase nor weechat can connect to irc.freenode.net 6666.  But if I go into client.c around line 448 and comment-out the block where it gets the port from ziz's server (irc_port = atoi(mom->content); )  it works fine with the hardcoded default port 6667.

Great game.  Would package for debian/ubuntu/mint if allowed.

**Comment by theZiz** [comment]
Hm, for me port 6666 is working. Maybe the port is blocked at your side? However I will add more ports to hase config so that a client can choose another one when a port is not working. :smile: 

Regarding your packaging attempts: Feel free to create packages, but try to keep track on changes :wink:
